# Generated by Django 4.1.5 on 2023-05-22 10:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIServices",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("service_key", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Au", "Audio"),
                            ("Vd", "Video"),
                            ("Im", "Image"),
                            ("St", "Satellite"),
                        ],
                        default="Vd",
                        max_length=2,
                    ),
                ),
                ("file_name", models.CharField(default=None, max_length=255)),
                ("base_url", models.CharField(max_length=200)),
                (
                    "processed_url",
                    models.CharField(default=None, max_length=200, null=True),
                ),
                ("recon_fixed", models.BooleanField(default=False)),
                ("drone_image", models.BooleanField(default=False)),
                ("drone_video", models.BooleanField(default=False)),
                ("recon_detection", models.BooleanField(default=False)),
                (
                    "kafka_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(db_index=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "service_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_service_type",
                        to="data_source.aiservices",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataSourceResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                ("confidence", models.TextField(null=True)),
                ("object_count", models.JSONField(null=True)),
                ("label", models.TextField(null=True)),
                ("bbox", models.TextField(null=True)),
                ("target", models.TextField(null=True)),
                ("time_taken", models.CharField(max_length=30, null=True)),
                ("video_metadata", models.JSONField(null=True)),
                ("satellite_image_data", models.JSONField(null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasource",
                        to="data_source.datasource",
                    ),
                ),
            ],
        ),
    ]
