# Generated by Django 4.1.5 on 2023-05-22 10:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                ("camera_name", models.CharField(default="Camera", max_length=25)),
                ("ip", models.CharField(max_length=25)),
                (
                    "container_id",
                    models.CharField(default=None, max_length=250, null=True),
                ),
                ("port", models.IntegerField()),
                (
                    "stream_url",
                    models.CharField(default=None, max_length=250, null=True),
                ),
                (
                    "camera_feed_url",
                    models.CharField(default=None, max_length=250, null=True),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[("rtsp", "rtsp"), ("rtmp", "rtmp")],
                        max_length=4,
                        null=True,
                    ),
                ),
                ("threats", models.JSONField(null=True)),
                (
                    "lat",
                    models.DecimalField(decimal_places=17, default=0.0, max_digits=20),
                ),
                (
                    "lng",
                    models.DecimalField(decimal_places=17, default=0.0, max_digits=20),
                ),
                (
                    "additional_parameters",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "out_port",
                    models.IntegerField(
                        default=None,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(9999),
                            django.core.validators.MinValueValidator(8888),
                        ],
                    ),
                ),
                (
                    "streaming_port",
                    models.IntegerField(
                        default=None,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(9999),
                            django.core.validators.MinValueValidator(8888),
                        ],
                    ),
                ),
                (
                    "ai_streaming_port",
                    models.IntegerField(
                        default=None,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(9999),
                            django.core.validators.MinValueValidator(8888),
                        ],
                    ),
                ),
                (
                    "docker_port_ml",
                    models.IntegerField(
                        default=None,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(5500),
                            django.core.validators.MinValueValidator(5400),
                        ],
                    ),
                ),
                ("is_drone_camera", models.BooleanField(default=False, null=True)),
                ("active_status", models.BooleanField(default=True, null=True)),
                ("is_stream", models.BooleanField(default=False, null=True)),
                ("username", models.CharField(blank=True, max_length=30, null=True)),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                ("location", models.CharField(max_length=228, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CameraResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                ("detections", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cameraresponse_camera",
                        to="camera.camera",
                    ),
                ),
            ],
        ),
    ]
