# Generated by Django 4.1.5 on 2023-05-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data_source", "0001_initial"),
        ("camera", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="service_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_type",
                to="data_source.aiservices",
            ),
        ),
    ]
