# Generated by Django 4.0.5 on 2023-06-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_live_stream',
            field=models.BooleanField(default=False),
        ),
    ]
