# Generated by Django 4.0.5 on 2023-06-02 06:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageServerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('file_path_local', models.CharField(blank=True, max_length=500, null=True)),
                ('wms_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('area_name', models.CharField(blank=True, max_length=500, null=True)),
                ('date_of_acquisition', models.DateField(blank=True, null=True)),
                ('resolution', models.IntegerField(blank=True, null=True)),
                ('data_source', models.IntegerField(blank=True, null=True)),
                ('image_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image Server Data',
                'verbose_name_plural': 'Image Server Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FootprintsGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='image_server_data', to='reconnaissance.imageserverdata')),
            ],
            options={
                'verbose_name': 'Foot Print Geometry',
                'verbose_name_plural': 'Foot Print Geometry',
                'ordering': ['-created_at'],
            },
        ),
    ]
