# Generated by Django 4.0.5 on 2023-06-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconnaissance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageserverdata',
            name='base_folder',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
