# Generated by Django 4.0.5 on 2023-06-08 10:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reconnaissance', '0004_alter_footprintsgeometry_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconnaissanceAIServices',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_key', models.CharField(blank=True, max_length=40, null=True)),
                ('service_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Reconnaissance AI Service',
                'verbose_name_plural': 'Reconnaissance AI Services',
            },
        ),
        migrations.RemoveField(
            model_name='imageserverdata',
            name='image_id',
        ),
        migrations.AddField(
            model_name='imageserverdata',
            name='image_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='ReconnaissanceAIResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kafka_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=20)),
                ('complete_ai_date', models.DateTimeField(blank=True, null=True)),
                ('is_processing', models.BooleanField(default=False)),
                ('geojson_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconnaissance_image', to='reconnaissance.imageserverdata')),
                ('reconnaissance_ai_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconnaissance_services', to='reconnaissance.reconnaissanceaiservices')),
            ],
            options={
                'verbose_name': 'Reconnaissance AI Result',
                'verbose_name_plural': 'Reconnaissance AI Results',
            },
        ),
    ]
