# Generated by Django 4.0.5 on 2023-06-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconnaissance', '0006_alter_imageserverdata_image_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconnaissanceairesults',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('failed', 'Failed'), ('completed', 'Completed')], default='processing', max_length=20),
        ),
    ]
