# Generated by Django 4.1.5 on 2023-05-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_alert_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_view",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
