# Generated by Django 4.1.5 on 2023-05-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_is_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="object_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
